FROM alpine:3.4
RUN touch /tmp/4e78ec3a990ab5b22acd13a78776455631d937b3
RUN apk update && apk upgrade && apk add build-base ruby ruby-dev ruby-irb ruby-bundler libffi-dev
RUN apk update && apk upgrade && apk add nginx
RUN adduser -D -h /home/bespoked -s /bin/bash bespoked
ADD . /home/bespoked
WORKDIR /home/bespoked
RUN bundle
CMD ["bundle", "exec" "ruby", "/home/bespoked/bespoked.rb"]
