---
apiVersion: v1
kind: Service
metadata:
  name: bespoked-service-alt
  namespace: default
spec:
  # The default backend must be of type NodePort.
  type: NodePort
  ports:
  - nodePort: 30011
    port: 8888
    targetPort: 8888
    protocol: TCP
    name: http
  selector:
    k8s-app: bespoked-alt
---
apiVersion: v1
kind: Service
metadata:
  name: bespoked-health-service-alt
  namespace: default
spec:
  # The default backend must be of type NodePort.
  type: NodePort
  ports:
  - nodePort: 30012
    port: 8889
    targetPort: 8889
    protocol: TCP
    name: http
  selector:
    k8s-app: bespoked-alt
---
apiVersion: v1
kind: Service
metadata:
  name: bespoked-dashboard-service-alt
  namespace: default
spec:
  # The default backend must be of type NodePort.
  type: NodePort
  ports:
  - nodePort: 30013
    port: 8890
    targetPort: 8890
    protocol: TCP
    name: http
  selector:
    k8s-app: bespoked-alt
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: bespoked-replication-controller-alt
  namespace: default
  labels:
    k8s-app: bespoked-alt
spec:
  #TODO: make this possible to have more than 1 controller alive simultaneously.
  replicas: 1
  selector:
    k8s-app: bespoked-alt
    version: rv1 #NOTE: this is re-written
  template:
    metadata:
      namespace: default
      labels:
        k8s-app: bespoked-alt
        version: rv1 #NOTE: this is re-written
    spec:
      terminationGracePeriodSeconds: 600
      serviceAccount: default
      imagePullSecrets:
        - name: dockercfgjson
      containers:
      - image: #NOTE: this is re-written via manifest.rb
        imagePullPolicy: Always
        env:
        name: bespoked-controller-alt
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        command: ["bundle", "exec", "ruby", "main.rb"]
