---
apiVersion: v1
kind: Service
metadata:
  name: bespoked-service
spec:
  # The default backend must be of type NodePort.
  type: NodePort
  ports:
  - nodePort: 30001
    port: 8888
    targetPort: 8181
    protocol: TCP
    name: http
  selector:
    k8s-app: bespoked
---
apiVersion: v1
kind: Service
metadata:
  name: bespoked-health-service
spec:
  # The default backend must be of type NodePort.
  type: NodePort
  ports:
  - nodePort: 30002
    port: 8889
    targetPort: 8182
    protocol: TCP
    name: http
  selector:
    k8s-app: bespoked
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: bespoked-replication-controller
  labels:
    k8s-app: bespoked
spec:
  #TODO: make this possible to have more than 1 controller alive simultaneously.
  replicas: 1
  selector:
    k8s-app: bespoked
    version: rv1 #NOTE: this is re-written
  template:
    metadata:
      labels:
        k8s-app: bespoked
        version: rv1 #NOTE: this is re-written
    spec:
      terminationGracePeriodSeconds: 600
      imagePullSecrets:
        - name: dockercfgjson
      containers:
      - image: #NOTE: this is re-written via manifest.rb
        imagePullPolicy: Always
        env:
        name: bespoked-controller
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        command: ["bundle", "exec", "ruby", "main.rb"]
